-- Add seq_id column to products
alter table public.products 
add column seq_id bigint generated by default as identity not null;

-- Be explicit about the sequence if we want to ensure it starts at 1 and increments? 
-- The default generated identity will handle 1, 2, 3...
