-- Create table for storing notification history
create table if not exists public.app_notifications (
    id bigint generated by default as identity primary key,
    title text not null,
    body text not null,
    url text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS
alter table public.app_notifications enable row level security;

-- Everyone can read notifications (they are public announcements)
create policy "Allow public read"
    on public.app_notifications
    for select
    using (true);

-- Only service_role (admin actions) can insert
create policy "Allow service_role insert"
    on public.app_notifications
    for insert
    with check (true); 
    -- Note: We rely on the server action using service_role client to insert.
