-- Create reviews table
create table if not exists public.reviews (
    id bigint generated by default as identity primary key,
    star integer not null check (star >= 1 and star <= 5),
    comment text,
    game_title text, -- e.g., "VALORANT", "FGO"
    manual_stock_no text, -- Manually entered stock number e.g. "No.123"
    manual_price integer, -- Manually entered price
    review_date date default current_date, -- Manually adjustable date
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security
alter table public.reviews enable row level security;

-- Policies
DROP POLICY IF EXISTS "Allow public read" ON public.reviews;
create policy "Allow public read" on public.reviews for select using (true);

DROP POLICY IF EXISTS "Allow admin all" ON public.reviews;
create policy "Allow admin all" on public.reviews for all using (auth.role() = 'service_role');
